(()=>{
const $=s=>document.querySelector(s); const wait=ms=>new Promise(r=>setTimeout(r,ms));
const ASSETS={berry1:'berry1.png',berry2:'berry2.png',berry3:'berry3.png',berry4:'berry4.png',berry5:'berry5.png',berry6:'berry6.png',berry7:'berry7.png',berry8:'berry8.png',berry9:'berry9.png',berry10:'berry10.png',giant:'giant.png',mother:'mother.png',perfect:'perfect.png',unripe:'unripe.png',leaf:'leaf.png',twig:'twig.png',bug:'bug.png',bugspray:'bugspray.png',organizer:'organizer.png',evie:'evie.png',spill:'spill.png',rain:'rain.png'};
const cardImage=c=>c?(c.img||ASSETS[c.id]||''):'';
let lastUid=null,revealing=false;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function stateLabel(p,isTurn){if(p.busted)return'BUCKET RUINED';if(p.takingBreak)return'TAKING A BREAK';return isTurn?'PICKING':'WAITING';}
function cardThumb(c,mini=false){return `<img class="card-thumb" src="${cardImage(c)}" alt="${esc(c.name||'Card')}" title="${esc(c.name||'Card')}">`;}
function playerTile(p,isTurn){const cards=p.cards?.length?p.cards.map(c=>cardThumb(c,true)).join(''):'<span class="empty-text">Empty bucket</span>';const initial=(p.name||'?').slice(0,1).toUpperCase();return `<article class="player-tile ${isTurn?'turn':''}"><div class="player-head"><div class="avatar">${esc(initial)}</div><div><div class="player-name">${esc(p.name)}</div><div class="player-status">${stateLabel(p,isTurn)}</div></div><div class="score-badge">${p.score}<small>BUCKET</small></div></div><div class="mini-bucket-row"><img class="mini-bucket" src="bucket.svg" alt=""><div class="mini-card-strip">${cards}</div></div><div class="trip-total">Trip total: <b>${p.total||0}</b>${p.multiplier>1?` • x${p.multiplier}`:''}${p.divisors?` • ÷${Math.pow(2,p.divisors)}`:''}</div></article>`;}
function render(state){
  const me=state.players.find(p=>p.isYou)||state.players[0]; const opponents=state.players.filter(p=>!p.isYou);
  const turnKey=state.turnKey; $('#handLabel').textContent=`${state.mode==='multi'?'Multiplayer • ':''}Hand ${state.hand} of ${state.maxHands||5}`;
  const opp=$('#opponents'); opp.classList.toggle('many',opponents.length>2); opp.innerHTML=opponents.map(p=>playerTile(p,p.key===turnKey&&!state.locked&&state.phase==='playing')).join('');
  const mineTurn=me&&me.key===turnKey&&!state.locked&&state.phase==='playing'&&!me.takingBreak&&!me.busted;
  const myCards=me?.cards?.length?me.cards.map(c=>cardThumb(c)).join(''):'<span class="empty-text">Your metal bucket is empty</span>';
  $('#yourPanel').className=`your-panel ${mineTurn?'turn':''}`; $('#yourPanel').innerHTML=`<div class="player-head"><div class="avatar">${esc((me?.name||'Y').slice(0,1).toUpperCase())}</div><div><div class="player-name">${esc(me?.name||'You')} <span style="color:#6a4b37">(You)</span></div><div class="player-status">${stateLabel(me||{},mineTurn)}</div></div><div class="score-badge">${me?.score||0}<small>BUCKET</small></div></div><div class="your-main"><div class="your-bucket-wrap"><img class="your-bucket" src="bucket.svg" alt="Your bucket"><div class="your-score">${me?.score||0}</div></div><div class="your-card-strip">${myCards}</div></div><div class="trip-total">Trip total: <b>${me?.total||0}</b>${me?.multiplier>1?` • Perfect Bush x${me.multiplier}`:''}${me?.divisors?` • Spill ÷${Math.pow(2,me.divisors)}`:''}</div>`;
  const latest=state.latestCard; if(latest){$('#latestCard').src=cardImage(latest);$('#latestCard').classList.remove('hidden');$('#latestPlaceholder').classList.add('hidden');const drawer=state.players.find(p=>p.key===latest.drawnByKey);$('#latestWho').textContent=drawer?`${drawer.name} drew this`:'';$('#latestWho').classList.toggle('hidden',!drawer);}else{$('#latestCard').classList.add('hidden');$('#latestPlaceholder').classList.remove('hidden');$('#latestWho').classList.add('hidden');}
  $('#pickBtn').disabled=!mineTurn;$('#breakBtn').disabled=!mineTurn;$('#deckButton').disabled=!mineTurn;
  if(state.phase==='inspection') $('#turnMessage').textContent='Bucket Inspection'; else if(mineTurn) $('#turnMessage').textContent='Your turn — Pick Another or Take a Break.'; else {const t=state.players.find(p=>p.key===turnKey);$('#turnMessage').textContent=t?`${t.name} is deciding…`:'Waiting…';}
  const lines=(state.log||[]).slice(-3).reverse(); $('#eventLog').innerHTML=lines.map(x=>`<div class="event-line">${esc(x)}</div>`).join('');
}
function ensureReveal(){let l=document.getElementById('drawRevealLayer');if(l)return l;l=document.createElement('div');l.id='drawRevealLayer';l.className='draw-reveal-layer';l.innerHTML='<div class="draw-reveal-caption"></div><img class="draw-reveal-card" alt="Drawn card">';document.body.appendChild(l);return l;}
async function revealCard(card,who=''){if(!card||revealing)return;revealing=true;const l=ensureReveal(),img=l.querySelector('img'),cap=l.querySelector('.draw-reveal-caption');cap.textContent=who?`${who} picked…`:'Card drawn';img.src=cardImage(card);img.alt=card.name||'Card';try{await img.decode()}catch(e){}l.classList.add('active');await wait(180);await wait(1000);const target=$('#latestCard');const from=img.getBoundingClientRect(),to=(target&&target.getBoundingClientRect().width)?target.getBoundingClientRect():{left:innerWidth/2-59,top:innerHeight/2-82,width:118,height:165};const dx=to.left-from.left,dy=to.top-from.top,sx=to.width/from.width,sy=to.height/from.height;const a=img.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${dx}px,${dy}px) scale(${sx},${sy})`,opacity:1}],{duration:360,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'});try{await a.finished}catch(e){}l.classList.remove('active');await wait(80);a.cancel();revealing=false;}
function maybeReveal(state){const c=state.latestCard;if(!c?.uid||c.uid===lastUid)return;lastUid=c.uid;const p=state.players.find(x=>x.key===c.drawnByKey);requestAnimationFrame(()=>revealCard(c,p?.name||''));}
function resetReveal(){lastUid=null;}
function openModal(title,content,actions=[]){$('#modalTitle').innerHTML=title;$('#modalContent').innerHTML=content;const a=$('#modalActions');a.innerHTML='';actions.forEach(x=>{const b=document.createElement('button');b.className='premium-btn target-btn';b.textContent=x.label;b.onclick=x.action;a.appendChild(b)});$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');}
function showEvie(targets,onChoose,actorName='You'){const content=`<div class="special-card"><img src="evie.png" alt="Evie — The Berry Bandit"></div><p class="target-prompt"><b>${esc(actorName)} drew Evie.</b><br>Choose who gets her. Evie removes that player's highest numbered huckleberry card.</p>`;openModal('Evie — The Berry Bandit',content,targets.map(t=>({label:`${t.name} — ${t.score} points`,action:()=>{closeModal();onChoose(t.key)}})));}
function showWaitingEvie(actorName){openModal('Evie!',`<div class="special-card"><img src="evie.png" alt="Evie"></div><p class="target-prompt"><b>${esc(actorName)}</b> is choosing which bucket Evie visits.</p>`,[]);}
async function showSpray(name,bug,spray){openModal('Bug Spray!',`<p class="target-prompt"><b>${esc(name)}</b> has a Bug and Bug Spray. Both remain visible for one second, then both are discarded.</p><div class="spray-pair"><img src="${cardImage(bug)}" alt="Bug"><img src="${cardImage(spray)}" alt="Bug Spray"></div>`,[]);await wait(1000);closeModal();}
function showInspection(state,onNext){const rows=[...(state.inspection?.rows||[])];const content=`${state.inspection?.reason?`<p class="target-prompt">${esc(state.inspection.reason)}</p>`:''}${rows.map(r=>`<div class="inspection-row"><span><b>${esc(r.name)}</b>${r.busted?' — Bucket Ruined':''}</span><b>${r.score}</b></div>`).join('')}<div class="winner-banner">${esc(state.inspection?.winnerName||'')} wins the hand!</div>`;openModal('Bucket Inspection',content,[{label:state.hand>=state.maxHands?'Final Results':'Next Hand',action:onNext}]);}
function showFinal(state,onAgain){const rows=state.finalRows||[];openModal('Trip Results',rows.map(r=>`<div class="inspection-row"><span><b>${esc(r.name)}</b></span><b>${r.total}</b></div>`).join('')+`<div class="winner-banner">${esc(rows[0]?.name||'')} wins the trip!</div>`,[{label:'Play Again',action:onAgain}]);}
function showRules(){openModal('How to Play','<p class="target-prompt"><b>Pick Another</b> to draw the top card. Every card takes effect immediately. Or choose <b>Take a Break</b> to lock your bucket for the rest of the hand.</p><p class="target-prompt"><b>Two Bugs</b> ruin your bucket. Bug Spray removes one Bug. Perfect Bush doubles your whole bucket. Evie removes a chosen player’s highest numbered huckleberry card. Bucket Spill divides a chosen bucket by two. Rain ends the hand instantly.</p><p class="target-prompt">Players taking a break can still be hit by Evie or Bucket Spill.</p>',[{label:'Got It',action:closeModal}]);}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.add('hidden'),1800);}
window.GameUI={ASSETS,cardImage,render,revealCard,maybeReveal,resetReveal,openModal,closeModal,showEvie,showWaitingEvie,showSpray,showInspection,showFinal,showRules,toast,wait};
})();
