(()=>{
const $=s=>document.querySelector(s);const wait=ms=>new Promise(r=>setTimeout(r,ms));
const ASSETS={berry3:'berry3.png',berry5:'berry5.png',berry7:'berry7.png',berry9:'berry9.png',berry11:'berry11.png',berry13:'berry13.png',berry15:'berry15.png',berry20:'berry20.png',leaf:'leaf.png',twig:'twig.png',bug:'bug.png',headhome:'headhome.png',evie:'evie.png',shake:'shake.png',pass:'pass.png',lucky:'lucky.png',mother:'mother.png'};
const cardImage=c=>c?(c.img||ASSETS[c.id]||'card-back.png'):'card-back.png';let lastUid=null,revealing=false;function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function stateLabel(p,isTurn){if(p.busted)return'BUSTED';if(p.out)return'HEAD HOME';return isTurn?'PICKING':'IN THE PATCH';}
function cardThumb(c){return `<img class="card-thumb" src="${cardImage(c)}" alt="${esc(c.name||'Card')}" title="${esc(c.name||'Card')}">`;}
function troubleLine(p){const t=p.trouble||{twig:0,leaf:0,bug:0};return `<div class="trouble-line"><span>🌿 ${t.twig}</span><span>🍂 ${t.leaf}</span><span>🐛 ${t.bug}</span>${p.evies?`<span>🐕 ${p.evies}</span>`:''}</div>`;}
function playerTile(p,isTurn){const cards=p.cards?.length?p.cards.map(cardThumb).join(''):'<span class="empty-text">No trouble yet</span>';const initial=(p.name||'?').slice(0,1).toUpperCase();return `<article class="player-tile ${isTurn?'turn':''} ${p.busted||p.out?'inactive':''}"><div class="player-head"><div class="avatar">${esc(initial)}</div><div><div class="player-name">${esc(p.name)}</div><div class="player-status">${stateLabel(p,isTurn)}</div></div><div class="score-badge">${p.total||0}<small>SCORE</small></div></div>${troubleLine(p)}<div class="mini-card-strip">${cards}</div></article>`;}
function render(state){const me=state.players.find(p=>p.isYou)||state.players[0],opponents=state.players.filter(p=>!p.isYou),turnKey=state.turnKey;$('#handLabel').textContent=`${state.mode==='multi'?'Multiplayer • ':''}Bucket ${state.hand} of ${state.maxHands||5}`;const opp=$('#opponents');opp.classList.toggle('many',opponents.length>2);opp.innerHTML=opponents.map(p=>playerTile(p,p.key===turnKey&&!state.locked&&state.phase==='playing')).join('');const mineTurn=me&&me.key===turnKey&&!state.locked&&state.phase==='playing'&&!me.out&&!me.busted;const myCards=me?.cards?.length?me.cards.map(cardThumb).join(''):'<span class="empty-text">No trouble yet</span>';$('#yourPanel').className=`your-panel ${mineTurn?'turn':''} ${me?.busted||me?.out?'inactive':''}`;$('#yourPanel').innerHTML=`<div class="player-head"><div class="avatar">${esc((me?.name||'Y').slice(0,1).toUpperCase())}</div><div><div class="player-name">${esc(me?.name||'You')} <span style="color:#6a4b37">(You)</span></div><div class="player-status">${stateLabel(me||{},mineTurn)}</div></div><div class="score-badge">${me?.total||0}<small>SCORE</small></div></div>${troubleLine(me||{})}<div class="your-card-strip">${myCards}</div>`;$('#potValue').textContent=state.pot||0;const latest=state.latestCard;if(latest){$('#latestCard').src=cardImage(latest);$('#latestCard').classList.remove('hidden');$('#latestPlaceholder').classList.add('hidden');const drawer=state.players.find(p=>p.key===latest.drawnByKey);$('#latestWho').textContent=drawer?`${drawer.name} drew this`:'';$('#latestWho').classList.toggle('hidden',!drawer)}else{$('#latestCard').classList.add('hidden');$('#latestPlaceholder').classList.remove('hidden');$('#latestWho').classList.add('hidden')}$('#pickBtn').disabled=!mineTurn;$('#deckButton').disabled=!mineTurn;if(state.phase==='inspection')$('#turnMessage').textContent='Bucket settled!';else if(mineTurn)$('#turnMessage').textContent='Your turn — draw one card.';else{const t=state.players.find(p=>p.key===turnKey);$('#turnMessage').textContent=t?`${t.name} is drawing…`:'Waiting…'}$('#eventLog').innerHTML=(state.log||[]).slice(-3).reverse().map(x=>`<div class="event-line">${esc(x)}</div>`).join('');}
function ensureReveal(){let l=document.getElementById('drawRevealLayer');if(l)return l;l=document.createElement('div');l.id='drawRevealLayer';l.className='draw-reveal-layer';l.innerHTML='<div class="draw-reveal-caption"></div><img class="draw-reveal-card" alt="Drawn card">';document.body.appendChild(l);return l;}
async function revealCard(card,who=''){if(!card||revealing)return;revealing=true;const l=ensureReveal(),img=l.querySelector('img'),cap=l.querySelector('.draw-reveal-caption');cap.textContent=who?`${who} picked…`:'Card drawn';img.src=cardImage(card);img.alt=card.name||'Card';try{await img.decode()}catch(e){}l.classList.add('active');await wait(180);await wait(1000);const target=$('#latestCard'),from=img.getBoundingClientRect(),to=(target&&target.getBoundingClientRect().width)?target.getBoundingClientRect():{left:innerWidth/2-59,top:innerHeight/2-82,width:118,height:165};const dx=to.left-from.left,dy=to.top-from.top,sx=to.width/from.width,sy=to.height/from.height;const a=img.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${dx}px,${dy}px) scale(${sx},${sy})`,opacity:1}],{duration:360,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'});try{await a.finished}catch(e){}l.classList.remove('active');await wait(80);a.cancel();revealing=false;}
function maybeReveal(state){const c=state.latestCard;if(!c?.uid||c.uid===lastUid)return;lastUid=c.uid;const p=state.players.find(x=>x.key===c.drawnByKey);requestAnimationFrame(()=>revealCard(c,p?.name||''));}function resetReveal(){lastUid=null;}
function openModal(title,content,actions=[]){$('#modalTitle').innerHTML=title;$('#modalContent').innerHTML=content;const a=$('#modalActions');a.innerHTML='';actions.forEach(x=>{const b=document.createElement('button');b.className='premium-btn target-btn';b.textContent=x.label;b.onclick=x.action;a.appendChild(b)});$('#modal').classList.remove('hidden');}function closeModal(){$('#modal').classList.add('hidden');}
function showHeadHome(pot,onTake,onStay){openModal('Head Home?',`<div class="special-card"><img src="headhome.png" alt="Head Home"></div><p class="target-prompt">Take <b>20 guaranteed berries</b> and leave this bucket — or stay in and fight for the <b>${pot} berries</b> in the middle.</p>`,[{label:'🏡 Take 20 & Head Home',action:onTake},{label:`🫐 Stay In for ${pot}`,action:onStay}]);}
function showInspection(state,onNext){const x=state.inspection||{},rows=x.rows||[];const evie=x.evieHits?`<p class="target-prompt">🐕 Evie struck ${x.evieHits} time${x.evieHits===1?'':'s'}, stealing ${x.evieHits*10} berries from the winner.</p>`:'';const content=`<p class="target-prompt">${esc(x.reason||'')}</p><div class="winner-banner">${x.winnerName?`${esc(x.winnerName)} wins the ${x.pot}-berry bucket!<br><small>Final bucket award: ${x.award}</small>`:'The bucket goes unclaimed.'}</div>${evie}${rows.map(r=>`<div class="inspection-row"><span><b>${esc(r.name)}</b>${r.busted?' — Busted':r.out?' — Headed Home':''}</span><b>${r.total}</b></div>`).join('')}`;openModal('Bucket Results',content,[{label:state.hand>=state.maxHands?'Final Results':'Next Bucket',action:onNext}]);}
function showFinal(state,onAgain){const rows=state.finalRows||[];openModal('Trip Results',rows.map(r=>`<div class="inspection-row"><span><b>${esc(r.name)}</b></span><b>${r.total}</b></div>`).join('')+`<div class="winner-banner">${esc(rows[0]?.name||'')} wins the trip!</div>`,[{label:'Play Again',action:onAgain}]);}
function showRules(){openModal('How to Play','<p class="target-prompt"><b>One shared bucket.</b> Every numbered Huckleberry card adds its berries to the pot in the middle.</p><p class="target-prompt"><b>Twigs, Leaves and Bugs are trouble.</b> Keep them face-up. Get <b>3 matching trouble cards</b> and you are BUSTED out of that bucket.</p><p class="target-prompt"><b>Head Home:</b> take 20 guaranteed berries and drop out, or stay in and fight for the whole pot. The last picker standing wins the shared bucket.</p><p class="target-prompt"><b>Evie:</b> save her. At the end, every Evie held by another player steals 10 berries from the bucket winner. Shake It Off removes one trouble card. Your Problem Now passes one trouble card. Lucky Patch doubles your next berry contribution. Mother Lode adds 25.</p>',[{label:'Got It',action:closeModal}]);}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.add('hidden'),1800)}window.GameUI={ASSETS,cardImage,render,revealCard,maybeReveal,resetReveal,openModal,closeModal,showHeadHome,showInspection,showFinal,showRules,toast,wait};
})();
