const socket=io(),$=s=>document.querySelector(s);let key=localStorage.getItem('cfcPlayerKey')||crypto.randomUUID(),name=localStorage.getItem('cfcPlayerName')||'',code='',maxPlayers=3;localStorage.setItem('cfcPlayerKey',key);nameInput.value=name;joinNameInput.value=name;
const q=new URLSearchParams(location.search).get('room');if(q){roomCodeInput.value=q.toUpperCase().slice(0,4);setTab('join')}
function setTab(t){const c=t==='create';createPane.classList.toggle('hidden',!c);joinPane.classList.toggle('hidden',c);createTab.classList.toggle('wood',!c);joinTab.classList.toggle('wood',c)}createTab.onclick=()=>setTab('create');joinTab.onclick=()=>setTab('join');
document.querySelectorAll('.player-count button').forEach(b=>b.onclick=()=>{maxPlayers=+b.dataset.n;document.querySelectorAll('.player-count button').forEach(x=>x.classList.toggle('selected',x===b))});
backBtn.onclick=()=>location.href='index.html';roomCodeInput.oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4);
function save(inp){name=inp.value.trim().replace(/\s+/g,' ').slice(0,18);localStorage.setItem('cfcPlayerName',name);return name}function err(t=''){entryError.textContent=t}
function ack(r){if(!r?.ok)return err(r?.message||'Unable to join room.');code=r.code;key=r.playerKey||key;localStorage.setItem('cfcPlayerKey',key);history.replaceState(null,'',`?room=${code}`);err('')}
createBtn.onclick=()=>{if(!save(nameInput))return err('Enter your name first.');socket.emit('createRoom',{name,playerKey:key,maxPlayers},ack)};joinBtn.onclick=()=>{if(!save(joinNameInput))return err('Enter your name first.');const c=roomCodeInput.value.trim().toUpperCase();if(c.length!==4)return err('Enter a 4-character room code.');socket.emit('joinRoom',{code:c,name,playerKey:key},ack)};
shareBtn.onclick=async()=>{const url=`${location.origin}/multiplayer.html?room=${code}`;try{if(navigator.share)await navigator.share({title:'Huckleberry Bucket',text:`Join my room ${code}`,url});else{await navigator.clipboard.writeText(url);showToast('Room link copied')}}catch(e){}};leaveBtn.onclick=()=>{socket.emit('leaveRoom');location.href='index.html'};startBtn.onclick=()=>socket.emit('startGame');
function showToast(t){toast.textContent=t;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),1600)}
socket.on('roomState',s=>{code=s.code;if(s.phase!=='lobby'){location.href=`game.html?mode=multi&room=${s.code}`;return}entryPanel.classList.add('hidden');roomPanel.classList.remove('hidden');roomCodeText.textContent=s.code;const me=s.players.find(p=>p.isYou);lobbyPlayers.innerHTML=s.players.map(p=>`<div class="lobby-person"><div class="lobby-avatar">${(p.name||'?')[0].toUpperCase()}</div><div class="grow"><b>${p.name}${p.isYou?' (You)':''}</b><br><small>${p.key===s.hostKey?'Room host':'Ready to pick'}</small></div><b>Ready</b></div>`).join('');startBtn.classList.toggle('hidden',me?.key!==s.hostKey);});socket.on('gameError',d=>err(d.message||'Game error'));
socket.on('connect',()=>{const c=q||code;if(c&&name)socket.emit('joinRoom',{code:c.toUpperCase(),name,playerKey:key},ack)});
