const express=require('express'),http=require('http'),{Server}=require('socket.io'),crypto=require('crypto'),path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||3000;app.use(express.static(__dirname));app.get('/health',(_r,res)=>res.json({ok:true}));
const rooms=new Map(),DRAW_REVEAL_MS=1550,TEMPLATE=[];const add=(n,c)=>{for(let i=0;i<n;i++)TEMPLATE.push({...c})};[[3,5],[5,5],[7,5],[9,5],[11,5],[13,5],[15,4],[20,2]].forEach(([v,n])=>add(n,{id:`berry${v}`,name:`${v} Huckleberries`,type:'berry',value:v}));add(7,{id:'twig',name:'Twig',type:'twig'});add(7,{id:'leaf',name:'Leaf',type:'leaf'});add(7,{id:'bug',name:'Bug',type:'bug'});add(4,{id:'headhome',name:'Head Home',type:'headhome',value:20});add(4,{id:'evie',name:'Evie — The Berry Bandit',type:'evie',value:10});add(2,{id:'shake',name:'Shake It Off',type:'shake'});add(2,{id:'pass',name:'Your Problem Now',type:'pass'});add(2,{id:'lucky',name:'Lucky Patch',type:'lucky'});add(1,{id:'mother',name:'Mother Lode',type:'mother',value:25});
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}let uid=0;const makeDeck=()=>shuffle(TEMPLATE.map(c=>({...c,uid:`m${Date.now()}-${uid++}`})));const cleanName=n=>String(n||'Picker').trim().replace(/\s+/g,' ').slice(0,18)||'Picker';function roomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c;do{c=Array.from({length:4},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}while(rooms.has(c));return c}
const player=({key,name,socketId})=>({key,name:cleanName(name),socketId,connected:true,total:0,cards:[],out:false,busted:false,evies:0,lucky:false});const active=p=>!p.out&&!p.busted;const trouble=(p,t)=>p.cards.filter(c=>c.type===t).length;const activeIndexes=r=>r.players.map((p,i)=>({p,i})).filter(x=>active(x.p));const log=(r,t)=>{r.log.push(t);if(r.log.length>40)r.log.shift()};
function serialize(r,youKey){return{code:r.code,hostKey:r.hostKey,mode:'multi',phase:r.phase,hand:r.hand,maxHands:r.maxHands,maxPlayers:r.maxPlayers,locked:r.locked,pot:r.pot,turnKey:r.players[r.turnIndex]?.key||null,latestCard:r.latestCard,pendingHomeKey:r.pendingHomeIndex==null?null:r.players[r.pendingHomeIndex]?.key,inspection:r.inspection,finalRows:r.finalRows,log:r.log,players:r.players.map(p=>({key:p.key,name:p.name,isYou:p.key===youKey,total:p.total,cards:p.cards,out:p.out,busted:p.busted,evies:p.evies,lucky:p.lucky,connected:p.connected,score:p.total,trouble:{twig:trouble(p,'twig'),leaf:trouble(p,'leaf'),bug:trouble(p,'bug')}}))}}
function emit(r){r.players.forEach(p=>{if(p.socketId)io.to(p.socketId).emit('roomState',serialize(r,p.key))})}const err=(s,m)=>s.emit('gameError',{message:m});function setSocket(s,r,p){if(s.data.roomCode)s.leave(s.data.roomCode);s.join(r.code);s.data.roomCode=r.code;s.data.playerKey=p.key;p.socketId=s.id;p.connected=true}const idxBySocket=(r,s)=>r.players.findIndex(p=>p.key===s.data.playerKey);
function beginHand(r){r.phase='playing';r.deck=makeDeck();r.pot=0;r.latestCard=null;r.pendingHomeIndex=null;r.locked=false;r.inspection=null;r.finalRows=null;r.players.forEach(p=>Object.assign(p,{cards:[],out:false,busted:false,evies:0,lucky:false}));r.turnIndex=(r.hand-1)%r.players.length;log(r,`Bucket ${r.hand}: a fresh shared bucket is on the table.`);emit(r)}
function nextActive(r,from){for(let k=1;k<=r.players.length;k++){const i=(from+k)%r.players.length;if(active(r.players[i]))return i}return-1}
function checkWinner(r){const a=activeIndexes(r);if(a.length===1){endHand(r,`${a[0].p.name} is the last picker standing!`,a[0].p);return true}if(a.length===0){endHand(r,'Nobody survived this bucket.',null);return true}return false}
function endHand(r,reason,winner){if(r.phase!=='playing')return;r.phase='inspection';r.locked=true;r.pendingHomeIndex=null;let evieHits=0,award=0;if(winner){evieHits=r.players.filter(p=>p!==winner).reduce((s,p)=>s+p.evies,0);award=Math.max(0,r.pot-evieHits*10);winner.total+=award}const rows=r.players.map(p=>({key:p.key,name:p.name,total:p.total,busted:p.busted,out:p.out,evies:p.evies})).sort((a,b)=>b.total-a.total);r.inspection={reason,rows,winnerName:winner?.name||'',pot:r.pot,evieHits,award};log(r,winner?`${winner.name} wins the ${r.pot}-berry bucket.`:'The bucket goes unclaimed.');emit(r)}
function advance(r,from){if(r.phase!=='playing'||checkWinner(r))return;const n=nextActive(r,from);if(n<0)return checkWinner(r);r.turnIndex=n;r.locked=false;emit(r)}
function finish(r,actor,delay=280){r.locked=false;emit(r);setTimeout(()=>advance(r,actor),delay)}
function resolveDraw(r,actor,c){if(r.phase!=='playing')return;const p=r.players[actor];if(c.type==='berry'){const amount=c.value*(p.lucky?2:1);r.pot+=amount;if(p.lucky){log(r,`Lucky Patch doubles it — ${amount} berries go into the bucket!`);p.lucky=false}else log(r,`${c.value} berries go into the shared bucket.`);return finish(r,actor)}if(['twig','leaf','bug'].includes(c.type)){p.cards.push(c);if(trouble(p,c.type)>=3){p.busted=true;log(r,`${p.name} collected 3 ${c.name}s and is BUSTED!`)}return finish(r,actor,380)}if(c.type==='evie'){p.evies++;p.cards.push(c);log(r,`${p.name} saves Evie for the eventual bucket winner.`);return finish(r,actor)}if(c.type==='mother'){r.pot+=25;log(r,'Mother Lode! 25 berries pour into the shared bucket.');return finish(r,actor,340)}if(c.type==='lucky'){p.lucky=true;p.cards.push(c);log(r,`${p.name}'s next Huckleberry card adds DOUBLE.`);return finish(r,actor)}if(c.type==='shake'){const opts=['twig','leaf','bug'].filter(t=>trouble(p,t)>0);if(opts.length){const t=opts.sort((a,b)=>trouble(p,b)-trouble(p,a))[0],i=p.cards.findIndex(x=>x.type===t);p.cards.splice(i,1);log(r,`${p.name} shakes off one ${t}.`)}else log(r,`${p.name} has no trouble to shake off.`);return finish(r,actor)}if(c.type==='pass'){const opts=['twig','leaf','bug'].filter(t=>trouble(p,t)>0),targets=activeIndexes(r).filter(x=>x.i!==actor);if(opts.length&&targets.length){const t=opts.sort((a,b)=>trouble(p,b)-trouble(p,a))[0],target=targets.sort((a,b)=>Math.max(trouble(b.p,'twig'),trouble(b.p,'leaf'),trouble(b.p,'bug'))-Math.max(trouble(a.p,'twig'),trouble(a.p,'leaf'),trouble(a.p,'bug')))[0],i=p.cards.findIndex(x=>x.type===t),card=p.cards.splice(i,1)[0];target.p.cards.push(card);log(r,`${p.name} passes a ${t} to ${target.p.name}.`);if(trouble(target.p,t)>=3){target.p.busted=true;log(r,`${target.p.name} now has 3 ${t}s and is BUSTED!`)}}else log(r,`${p.name} can't use Your Problem Now.`);return finish(r,actor,380)}if(c.type==='headhome'){r.pendingHomeIndex=actor;r.locked=true;log(r,`${p.name} must choose: 20 guaranteed berries or stay in for the pot.`);return emit(r)}}
io.on('connection',s=>{
 s.on('createRoom',({name,playerKey,maxPlayers}={},ack=()=>{})=>{const key=String(playerKey||crypto.randomUUID()).slice(0,80),code=roomCode(),p=player({key,name,socketId:s.id}),r={code,hostKey:key,phase:'lobby',hand:1,maxHands:5,maxPlayers:Math.max(2,Math.min(6,Number(maxPlayers)||3)),turnIndex:0,players:[p],deck:[],pot:0,latestCard:null,pendingHomeIndex:null,locked:false,inspection:null,finalRows:null,log:[]};rooms.set(code,r);setSocket(s,r,p);log(r,`${p.name} created room ${code}.`);ack({ok:true,code,playerKey:key});emit(r)});
 s.on('joinRoom',({code,name,playerKey}={},ack=()=>{})=>{code=String(code||'').toUpperCase().trim();const r=rooms.get(code);if(!r)return ack({ok:false,message:'Room not found.'});const key=String(playerKey||crypto.randomUUID()).slice(0,80);let p=r.players.find(x=>x.key===key);if(p){p.name=cleanName(name||p.name);setSocket(s,r,p);ack({ok:true,code,playerKey:key,rejoined:true});return emit(r)}if(r.phase!=='lobby')return ack({ok:false,message:'That game has already started.'});if(r.players.length>=r.maxPlayers)return ack({ok:false,message:'That room is full.'});p=player({key,name,socketId:s.id});r.players.push(p);setSocket(s,r,p);log(r,`${p.name} joined the picking crew.`);ack({ok:true,code,playerKey:key});emit(r)});
 s.on('startGame',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;const i=idxBySocket(r,s);if(i<0||r.players[i].key!==r.hostKey)return err(s,'Only the host can start the game.');if(r.players.length<2)return err(s,'At least 2 players are needed.');r.hand=1;r.players.forEach(p=>p.total=0);beginHand(r)});
 s.on('drawCard',()=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='playing'||r.locked)return;const i=idxBySocket(r,s);if(i!==r.turnIndex)return err(s,'It is not your turn.');if(!active(r.players[i]))return;r.locked=true;if(!r.deck.length)r.deck=makeDeck();const c=r.deck.pop();c.drawnByKey=r.players[i].key;r.latestCard=c;log(r,`${r.players[i].name} drew ${c.name}.`);emit(r);setTimeout(()=>resolveDraw(r,i,c),DRAW_REVEAL_MS)});
 s.on('headHomeChoice',({take}={})=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='playing'||r.pendingHomeIndex==null)return;const i=idxBySocket(r,s);if(i!==r.pendingHomeIndex)return err(s,'That choice belongs to another player.');const p=r.players[i];r.pendingHomeIndex=null;if(take){p.total+=20;p.out=true;log(r,`${p.name} Heads Home with 20 guaranteed berries.`)}else log(r,`${p.name} turns down 20 and stays in for the ${r.pot}-berry bucket!`);finish(r,i,220)});
 s.on('nextHand',()=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='inspection')return;const i=idxBySocket(r,s);if(i<0||r.players[i].key!==r.hostKey)return;if(r.hand>=r.maxHands){r.phase='final';r.finalRows=[...r.players].sort((a,b)=>b.total-a.total).map(p=>({name:p.name,total:p.total}));return emit(r)}r.hand++;beginHand(r)});
 s.on('disconnect',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;const i=idxBySocket(r,s);if(i>=0){r.players[i].connected=false;r.players[i].socketId=null;emit(r)}});
});
server.listen(PORT,()=>console.log(`Huckleberry Bucket listening on ${PORT}`));
