const express=require('express');const http=require('http');const {Server}=require('socket.io');const crypto=require('crypto');const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server);const PORT=process.env.PORT||3000;app.use(express.static(__dirname));app.get('/health',(_r,res)=>res.json({ok:true}));
const rooms=new Map();const DRAW_REVEAL_MS=1700;
const TEMPLATE=[];const add=(n,c)=>{for(let i=0;i<n;i++)TEMPLATE.push({...c})};for(let n=1;n<=10;n++){const count=n<=2?7:n<=4?6:n<=6?5:n<=8?4:3;add(count,{id:`berry${n}`,name:`${n} Huckleberr${n===1?'y':'ies'}`,type:'berry',value:n})}add(2,{id:'giant',name:'Giant Cluster',type:'berry',value:12});add(2,{id:'mother',name:'Mother Lode',type:'berry',value:15});add(2,{id:'perfect',name:'Perfect Bush',type:'perfect'});add(10,{id:'unripe',name:'Unripe Berries',type:'unripe',value:0});add(7,{id:'leaf',name:'Leaf',type:'leaf',value:-1});add(6,{id:'twig',name:'Twig',type:'twig',value:-2});add(7,{id:'bug',name:'Bug',type:'bug'});add(4,{id:'bugspray',name:'Bug Spray',type:'bugspray'});add(3,{id:'organizer',name:'Bucket Organizer',type:'organizer'});add(4,{id:'evie',name:'Evie',type:'evie'});add(3,{id:'spill',name:'Bucket Spill',type:'spill'});add(4,{id:'rain',name:'Rain',type:'rain'});
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}let uid=0;function makeDeck(){return shuffle(TEMPLATE.map(c=>({...c,uid:`m${Date.now()}-${uid++}`})))}
function cleanName(n){return String(n||'Picker').trim().replace(/\s+/g,' ').slice(0,18)||'Picker'}function roomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c;do{c=Array.from({length:4},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}while(rooms.has(c));return c}
function player({key,name,socketId}){return{key,name:cleanName(name),socketId,connected:true,total:0,cards:[],takingBreak:false,busted:false,multiplier:1,divisors:0,discarded:[]}}
function score(p){if(p.busted)return 0;let n=p.cards.reduce((s,c)=>s+(['berry','unripe','leaf','twig'].includes(c.type)?(c.value||0):0),0);n*=p.multiplier;n=Math.floor(n/Math.pow(2,p.divisors));return Math.max(0,n)}function active(p){return!p.takingBreak&&!p.busted}function activeIndexes(r){return r.players.map((p,i)=>({p,i})).filter(x=>active(x.p))}function remove(p,u){const i=p.cards.findIndex(c=>c.uid===u);return i>=0?p.cards.splice(i,1)[0]:null}
function log(r,t){r.log.push(t);if(r.log.length>40)r.log.shift()}
function serialize(r,youKey){return{code:r.code,hostKey:r.hostKey,mode:'multi',phase:r.phase,hand:r.hand,maxHands:r.maxHands,maxPlayers:r.maxPlayers,locked:r.locked,turnKey:r.players[r.turnIndex]?.key||null,latestCard:r.latestCard,pendingTarget:r.pendingTarget?{actorKey:r.players[r.pendingTarget.actorIndex]?.key,card:r.pendingTarget.card,allowedKeys:r.pendingTarget.allowedIndexes.map(i=>r.players[i]?.key).filter(Boolean)}:null,inspection:r.inspection,finalRows:r.finalRows,log:r.log,players:r.players.map(p=>({key:p.key,name:p.name,isYou:p.key===youKey,total:p.total,cards:p.cards,takingBreak:p.takingBreak,busted:p.busted,multiplier:p.multiplier,divisors:p.divisors,connected:p.connected,score:score(p)}))}}
function emit(r){r.players.forEach(p=>{if(p.socketId)io.to(p.socketId).emit('roomState',serialize(r,p.key))})}function err(s,m){s.emit('gameError',{message:m})}
function setSocket(s,r,p){if(s.data.roomCode)s.leave(s.data.roomCode);s.join(r.code);s.data.roomCode=r.code;s.data.playerKey=p.key;p.socketId=s.id;p.connected=true}
function idxBySocket(r,s){return r.players.findIndex(p=>p.key===s.data.playerKey)}
function beginHand(r){r.phase='playing';r.deck=makeDeck();r.latestCard=null;r.pendingTarget=null;r.locked=false;r.inspection=null;r.finalRows=null;r.players.forEach(p=>Object.assign(p,{cards:[],takingBreak:false,busted:false,multiplier:1,divisors:0,discarded:[]}));r.turnIndex=(r.hand-1)%r.players.length;log(r,`Hand ${r.hand}: everyone arrives at the berry patch.`);emit(r)}
function nextActive(r,from){for(let k=1;k<=r.players.length;k++){const i=(from+k)%r.players.length;if(active(r.players[i]))return i}return-1}
function endHand(r,reason){if(r.phase!=='playing')return;r.phase='inspection';r.locked=true;r.pendingTarget=null;const rows=r.players.map(p=>({key:p.key,name:p.name,score:score(p),busted:p.busted})).sort((a,b)=>b.score-a.score);r.players.forEach(p=>p.total+=score(p));r.inspection={reason,rows,winnerName:rows[0]?.name||''};log(r,`Bucket Inspection: ${rows[0]?.name||'Nobody'} wins the hand.`);emit(r)}
function advance(r,from){if(r.phase!=='playing')return;const act=activeIndexes(r);if(!act.length)return endHand(r,'Everyone took a break or ruined their bucket.');const n=nextActive(r,from);if(n<0)return endHand(r,'Everyone took a break or ruined their bucket.');r.turnIndex=n;r.locked=false;emit(r)}
function targets(r,actor){const a=activeIndexes(r);if(a.length===1&&a[0].i===actor)return[actor];return r.players.map((_p,i)=>i).filter(i=>i!==actor)}
function spray(r,actor,bug,sprayCard){const p=r.players[actor];r.locked=true;emit(r);io.to(r.code).emit('sprayAnimation',{playerKey:p.key,playerName:p.name,bugCard:bug,sprayCard,duration:1000});setTimeout(()=>{const b=remove(p,bug.uid),s=remove(p,sprayCard.uid);if(b)p.discarded.push(b);if(s)p.discarded.push(s);log(r,`${p.name} sprays the Bug. Both cards are discarded.`);r.latestCard=null;r.locked=false;emit(r);setTimeout(()=>advance(r,actor),180)},1000)}
function resolveDraw(r,actor,c){if(r.phase!=='playing')return;const p=r.players[actor];if(c.type==='rain'){log(r,`${p.name} drew Rain. The hand ends immediately!`);emit(r);return setTimeout(()=>endHand(r,'Rain ended the hand.'),350)}if(['berry','unripe','leaf','twig'].includes(c.type)){p.cards.push(c);r.locked=false;emit(r);return setTimeout(()=>advance(r,actor),260)}if(c.type==='perfect'){p.cards.push(c);p.multiplier*=2;log(r,`${p.name} found a Perfect Bush — bucket x${p.multiplier}.`);r.locked=false;emit(r);return setTimeout(()=>advance(r,actor),320)}if(c.type==='bug'){p.cards.push(c);const s=p.cards.find(x=>x.type==='bugspray');if(s)return spray(r,actor,c,s);if(p.cards.filter(x=>x.type==='bug').length>=2){p.busted=true;log(r,`${p.name}'s bucket is ruined by two Bugs!`)}r.locked=false;emit(r);return setTimeout(()=>advance(r,actor),320)}if(c.type==='bugspray'){p.cards.push(c);const b=p.cards.find(x=>x.type==='bug');if(b)return spray(r,actor,b,c);log(r,`${p.name} keeps Bug Spray ready.`);r.locked=false;emit(r);return setTimeout(()=>advance(r,actor),280)}if(c.type==='organizer'){p.cards.push(c);const junk=p.cards.find(x=>x.type==='twig')||p.cards.find(x=>x.type==='leaf');if(junk){remove(p,junk.uid);remove(p,c.uid);p.discarded.push(junk,c);log(r,`${p.name} uses Bucket Organizer to discard ${junk.name}.`)}else{remove(p,c.uid);p.discarded.push(c);log(r,`${p.name}'s bucket was already tidy.`)}r.locked=false;emit(r);return setTimeout(()=>advance(r,actor),300)}if(c.type==='evie'||c.type==='spill'){const allowed=targets(r,actor);r.pendingTarget={actorIndex:actor,card:c,allowedIndexes:allowed};r.locked=true;log(r,c.type==='evie'?`${p.name} drew Evie and must choose a bucket.`:`${p.name} drew Bucket Spill and must choose a bucket.`);emit(r);if(allowed.length===1)setTimeout(()=>resolveTarget(r,actor,allowed[0]),700)}}
function resolveTarget(r,actor,target){const q=r.pendingTarget;if(!q||q.actorIndex!==actor||!q.allowedIndexes.includes(target))return false;const a=r.players[actor],t=r.players[target],c=q.card;r.pendingTarget=null;if(c.type==='evie'){const berries=t.cards.filter(x=>x.type==='berry');if(berries.length){const high=berries.reduce((x,y)=>x.value>=y.value?x:y);const rm=remove(t,high.uid);if(rm)t.discarded.push(rm);log(r,`${a.name} sends Evie to ${t.name}. She eats the ${high.value}-point huckleberry card.`)}else log(r,`Evie visits ${t.name}, but finds no ripe berries.`);a.discarded.push(c)}else{t.divisors++;a.discarded.push(c);log(r,`${a.name} spills ${t.name}'s bucket — divide by 2.`)}r.latestCard=null;r.locked=false;emit(r);setTimeout(()=>advance(r,actor),360);return true}
io.on('connection',s=>{
 s.on('createRoom',({name,playerKey,maxPlayers}={},ack=()=>{})=>{const key=String(playerKey||crypto.randomUUID()).slice(0,80),code=roomCode(),p=player({key,name,socketId:s.id}),r={code,hostKey:key,phase:'lobby',hand:1,maxHands:5,maxPlayers:Math.max(2,Math.min(6,Number(maxPlayers)||3)),turnIndex:0,players:[p],deck:[],latestCard:null,pendingTarget:null,locked:false,inspection:null,finalRows:null,log:[]};rooms.set(code,r);setSocket(s,r,p);log(r,`${p.name} created room ${code}.`);ack({ok:true,code,playerKey:key});emit(r)});
 s.on('joinRoom',({code,name,playerKey}={},ack=()=>{})=>{code=String(code||'').toUpperCase().trim();const r=rooms.get(code);if(!r)return ack({ok:false,message:'Room not found.'});const key=String(playerKey||crypto.randomUUID()).slice(0,80);let p=r.players.find(x=>x.key===key);if(p){p.name=cleanName(name||p.name);setSocket(s,r,p);ack({ok:true,code,playerKey:key,rejoined:true});emit(r);return}if(r.phase!=='lobby')return ack({ok:false,message:'That game has already started.'});if(r.players.length>=r.maxPlayers)return ack({ok:false,message:'That room is full.'});p=player({key,name,socketId:s.id});r.players.push(p);setSocket(s,r,p);log(r,`${p.name} joined the picking crew.`);ack({ok:true,code,playerKey:key});emit(r)});
 s.on('startGame',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;const i=idxBySocket(r,s);if(i<0||r.players[i].key!==r.hostKey)return err(s,'Only the host can start the game.');if(r.players.length<2)return err(s,'At least 2 players are needed.');r.hand=1;r.players.forEach(p=>p.total=0);beginHand(r)});
 s.on('pickAnother',()=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='playing'||r.locked)return;const i=idxBySocket(r,s);if(i!==r.turnIndex)return err(s,'It is not your turn.');const p=r.players[i];if(!active(p))return;r.locked=true;const c=r.deck.pop()||makeDeck().pop();c.drawnByKey=p.key;r.latestCard=c;log(r,`${p.name} drew ${c.name}.`);emit(r);setTimeout(()=>resolveDraw(r,i,c),DRAW_REVEAL_MS)});
 s.on('takeBreak',()=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='playing'||r.locked)return;const i=idxBySocket(r,s);if(i!==r.turnIndex)return err(s,'It is not your turn.');const p=r.players[i];if(!active(p))return;p.takingBreak=true;log(r,`${p.name} takes a break with ${score(p)} points.`);emit(r);setTimeout(()=>advance(r,i),330)});
 s.on('chooseTarget',({targetKey}={})=>{const r=rooms.get(s.data.roomCode);if(!r||!r.pendingTarget)return;const i=idxBySocket(r,s);if(i!==r.pendingTarget.actorIndex)return;const t=r.players.findIndex(p=>p.key===targetKey);resolveTarget(r,i,t)});
 s.on('nextHand',()=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='inspection')return;if(r.hand>=r.maxHands){r.phase='final';r.finalRows=[...r.players].sort((a,b)=>b.total-a.total).map(p=>({key:p.key,name:p.name,total:p.total}));emit(r)}else{r.hand++;beginHand(r)}});
 s.on('restartGame',()=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='final')return;r.hand=1;r.players.forEach(p=>p.total=0);beginHand(r)});
 s.on('leaveRoom',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;const i=idxBySocket(r,s);if(i>=0){const [p]=r.players.splice(i,1);log(r,`${p.name} left the room.`);if(p.key===r.hostKey)r.hostKey=r.players[0]?.key||null;if(!r.players.length)rooms.delete(r.code);else emit(r)}s.leave(r.code);s.data.roomCode=null;s.data.playerKey=null});
 s.on('disconnect',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;const i=idxBySocket(r,s);if(i>=0&&r.players[i].socketId===s.id){r.players[i].connected=false;r.players[i].socketId=null;emit(r)}});
});
server.listen(PORT,()=>console.log(`Clark Family Cabin V12 running on ${PORT}`));
