const $=s=>document.querySelector(s); const wait=ms=>new Promise(r=>setTimeout(r,ms));
const IM={berry:n=>`berry${n}.png`,giant:'giant.png',mother:'mother.png',perfect:'perfect.png',unripe:'unripe.png',leaf:'leaf.png',twig:'twig.png',bug:'bug.png',bugspray:'bugspray.png',organizer:'organizer.png',evie:'evie.png',spill:'spill.png',rain:'rain.png'};
const T=[];const add=(n,c)=>{for(let i=0;i<n;i++)T.push({...c})};for(let n=1;n<=10;n++){let count=n<=2?7:n<=4?6:n<=6?5:n<=8?4:3;add(count,{id:'berry'+n,name:n+' Huckleberr'+(n===1?'y':'ies'),type:'berry',value:n,img:IM.berry(n)})}add(2,{id:'giant',name:'Giant Cluster',type:'berry',value:12,img:IM.giant});add(2,{id:'mother',name:'Mother Lode',type:'berry',value:15,img:IM.mother});add(2,{id:'perfect',name:'Perfect Bush',type:'perfect',img:IM.perfect});add(10,{id:'unripe',name:'Unripe Berries',type:'unripe',value:0,img:IM.unripe});add(7,{id:'leaf',name:'Leaf',type:'leaf',value:-1,img:IM.leaf});add(6,{id:'twig',name:'Twig',type:'twig',value:-2,img:IM.twig});add(7,{id:'bug',name:'Bug',type:'bug',img:IM.bug});add(4,{id:'bugspray',name:'Bug Spray',type:'bugspray',img:IM.bugspray});add(3,{id:'organizer',name:'Bucket Organizer',type:'organizer',img:IM.organizer});add(4,{id:'evie',name:'Evie',type:'evie',img:IM.evie});add(3,{id:'spill',name:'Bucket Spill',type:'spill',img:IM.spill});add(4,{id:'rain',name:'Rain',type:'rain',img:IM.rain});
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function deck(){return shuffle(T.map((c,i)=>({...c,uid:Date.now()+'-'+i+'-'+Math.random()})))}
function fresh(name,index,style){return{name,index,style,total:0,cards:[],takingBreak:false,busted:false,multiplier:1,divisors:0,discarded:[]}}
let P=[fresh('Mara',0,'careful'),fresh('Cole',1,'bold'),fresh('You',2,'player')],D=[],turn=2,hand=1,locked=false,latest=null,finished=false;
function score(p){if(p.busted)return 0;let s=p.cards.reduce((a,c)=>a+((c.type==='berry'||['unripe','leaf','twig'].includes(c.type))?(c.value||0):0),0);s*=p.multiplier;s=Math.floor(s/Math.pow(2,p.divisors));return Math.max(0,s)}function active(p){return !p.takingBreak&&!p.busted}
function resetHand(){D=deck();P.forEach(p=>{p.cards=[];p.takingBreak=false;p.busted=false;p.multiplier=1;p.divisors=0;p.discarded=[]});turn=2;locked=false;latest=null;finished=false;$('#handLabel').textContent=`Hand ${hand} of 5 • Single Player`;logClear();log('🚚 Everyone grabs a metal bucket and starts picking.');render();setMessage()}
function img(c){return c.img}function playerHTML(p,you=false){let state=p.busted?'BUCKET RUINED':p.takingBreak?'TAKING A BREAK':(p.index===turn&&!locked?'PICKING':'WAITING');let cards=p.cards.length?p.cards.map(c=>`<div class="bucket-card"><img src="${img(c)}" alt="${c.name}"></div>`).join(''):'<div class="empty-bucket">Empty metal bucket</div>';return `<article class="player-card ${you?'you':''} ${p.index===turn&&!locked?'turn':''}"><div class="player-head"><div class="avatar">${p.index===0?'M':p.index===1?'C':'Y'}</div><div><div class="player-name">${p.name}${you?' (You)':''}</div><div class="player-state">${state}</div></div><div class="score-badge">${score(p)}<br><small>BUCKET</small></div></div><div class="bucket-strip">${cards}</div><div class="player-state">Trip total: <b>${p.total}</b>${p.multiplier>1?` • Perfect Bush x${p.multiplier}`:''}${p.divisors?` • Spill ÷${Math.pow(2,p.divisors)}`:''}</div></article>`}
function render(){$('#opponents').innerHTML=P.slice(0,2).map(p=>playerHTML(p)).join('');$('#playerPanel').innerHTML=playerHTML(P[2],true);if(latest){$('#latestCard').src=img(latest.card);$('#latestCard').classList.remove('hidden');$('#latestPlaceholder').classList.add('hidden');$('#latestWho').textContent=latest.name+' drew this'}else{$('#latestCard').classList.add('hidden');$('#latestPlaceholder').classList.remove('hidden');$('#latestWho').textContent=''}let mine=turn===2&&active(P[2])&&!locked&&!finished;$('#pickBtn').disabled=!mine;$('#breakBtn').disabled=!mine;$('#deckButton').disabled=!mine}
function logClear(){$('#eventLog').innerHTML=''}function log(t){let d=document.createElement('div');d.className='event-line';d.textContent=t;$('#eventLog').prepend(d)}function setMessage(){if(finished)return;$('#message').textContent=turn===2?'Your turn — Pick Another or Take a Break.':`${P[turn].name} is deciding…`}
function next(){if(P.every(p=>!active(p)))return endHand('Everyone is done picking.');for(let k=1;k<=P.length;k++){let i=(turn+k)%P.length;if(active(P[i])){turn=i;render();setMessage();if(i!==2)setTimeout(aiTurn,650);return}}endHand('Everyone is done picking.')}
async function drawCard(i){if(locked||finished||!active(P[i]))return;locked=true;render();let c=D.pop()||deck().pop();P[i].cards.push(c);latest={card:c,name:P[i].name};log(`${P[i].name} drew ${c.name}.`);render();await wait(500);await resolve(i,c);locked=false;render();if(!finished)next()}
async function resolve(i,c){let p=P[i];if(c.type==='bug'){let spray=p.cards.find(x=>x.type==='bugspray');let bugs=p.cards.filter(x=>x.type==='bug');if(spray&&bugs.length){await sprayPair(p,bugs[0],spray)}else if(bugs.length>=2){p.busted=true;log(`${p.name}'s bucket is ruined by two Bugs!`)}}
else if(c.type==='bugspray'){let bug=p.cards.find(x=>x.type==='bug');if(bug)await sprayPair(p,bug,c)}
else if(c.type==='organizer'){let j=p.cards.findIndex(x=>x.type==='twig'||x.type==='leaf');if(j>=0){let r=p.cards.splice(j,1)[0];p.discarded.push(r);log(`${p.name} removes a ${r.name}.`)}}
else if(c.type==='perfect'){p.multiplier*=2;log(`${p.name}'s Perfect Bush doubles the bucket!`)}
else if(c.type==='evie'){let t=await target(i,'evie',c);let berries=P[t].cards.filter(x=>x.type==='berry');let evieIndex=p.cards.findIndex(x=>x.uid===c.uid);if(evieIndex>=0)p.discarded.push(...p.cards.splice(evieIndex,1));if(berries.length){let hi=berries.reduce((a,b)=>a.value>=b.value?a:b);let hiIndex=P[t].cards.findIndex(x=>x.uid===hi.uid);if(hiIndex>=0)P[t].discarded.push(...P[t].cards.splice(hiIndex,1));log(`Evie eats ${P[t].name}'s ${hi.value}-point card.`)}else{log(`Evie visits ${P[t].name}, but there are no ripe huckleberries to eat.`)}latest=null;render()}
else if(c.type==='spill'){let t=await target(i,'spill');P[t].divisors++;log(`${P[t].name}'s bucket is cut in half.`)}
else if(c.type==='rain'){log('🌧 Rain! Bucket Inspection begins.');await wait(500);endHand('Rain ended the hand.')}}
async function sprayPair(p,bug,spray){log(`${p.name} has a Bug and Bug Spray — both stay visible for one second.`);render();openModal('🧴 Bug Spray!',`<p><b>${p.name}</b> sprays the Bug. Both cards will be discarded.</p><div class="spray-pair"><img src="${bug.img}"><img src="${spray.img}"></div>`,[]);await wait(1000);closeModal();for(let c of [bug,spray]){let k=p.cards.findIndex(x=>x.uid===c.uid);if(k>=0)p.discarded.push(...p.cards.splice(k,1))}log(`${p.name} discarded the Bug and Bug Spray.`)}
function targetOptions(actor){let act=P.map((p,i)=>({p,i})).filter(x=>active(x.p));if(act.length===1&&act[0].i===actor)return [actor];return P.map((p,i)=>i).filter(i=>i!==actor)}
async function target(actor,type,card=null){let list=targetOptions(actor);if(actor!==2)return list.sort((a,b)=>score(P[b])-score(P[a]))[0];if(list.length===1)return list[0];return new Promise(res=>{let isEvie=type==='evie';let content=isEvie?`<div class="special-target-card"><img src="${(card||{img:IM.evie}).img}" alt="Evie — The Berry Bandit"></div><p class="target-prompt"><b>Who should Evie visit?</b><br>She will eat that player's highest numbered huckleberry card.</p>`:'<p class="target-prompt">Choose whose bucket should be cut in half.</p>';openModal(isEvie?'🐶 Evie — The Berry Bandit':'🪣 Bucket Spill',content,list.map(i=>({label:`${P[i].name} — ${score(P[i])} points`,action:()=>{closeModal();res(i)}})))})}
function aiBreak(p){let s=score(p),bugs=p.cards.filter(c=>c.type==='bug').length;if(bugs===1&&s>=10)return Math.random()<.82;if(p.style==='careful'&&s>=17)return Math.random()<.72;if(p.style==='bold'&&s>=28)return Math.random()<.45;return false}async function aiTurn(){if(finished||turn===2)return;let p=P[turn];if(aiBreak(p)){p.takingBreak=true;log(`${p.name} takes a break with ${score(p)}.`);render();setTimeout(next,500)}else drawCard(turn)}
function endHand(reason){if(finished)return;finished=true;locked=true;let rows=P.map(p=>({p,s:score(p)})).sort((a,b)=>b.s-a.s);P.forEach(p=>p.total+=score(p));openModal('🪣 Bucket Inspection',`<p>${reason}</p>${rows.map(x=>`<div class="inspection-row"><span><b>${x.p.name}</b>${x.p.busted?' — Bucket Ruined':''}</span><b>${x.s}</b></div>`).join('')}<div class="winner-banner">${rows[0].p.name} wins the hand!</div>`,[{label:hand>=5?'Final Results':'Next Hand',action:()=>{closeModal();if(hand>=5)finalResults();else{hand++;resetHand()}}}]);render()}
function finalResults(){let rows=[...P].sort((a,b)=>b.total-a.total);openModal('🏆 Trip Results',rows.map(p=>`<div class="inspection-row"><span><b>${p.name}</b></span><b>${p.total}</b></div>`).join('')+`<div class="winner-banner">${rows[0].name} wins the trip!</div>`,[{label:'Play Again',action:()=>location.reload()}])}
function openModal(t,c,acts){$('#modalTitle').innerHTML=t;$('#modalContent').innerHTML=c;let a=$('#modalActions');a.innerHTML='';acts.forEach(x=>{let b=document.createElement('button');b.textContent=x.label;b.onclick=x.action;a.appendChild(b)});$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
$('#pickBtn').onclick=()=>drawCard(2);$('#deckButton').onclick=()=>drawCard(2);$('#breakBtn').onclick=()=>{if(turn!==2||locked)return;P[2].takingBreak=true;log(`You take a break with ${score(P[2])}.`);render();next()};$('#homeBtn').onclick=()=>location.href='index.html';$('#rulesBtn').onclick=()=>openModal('How to Play','<p>Choose <b>Pick Another</b> or <b>Take a Break</b>. Every drawn card takes effect immediately. Two Bugs ruin your bucket. Bug Spray cancels a Bug. Perfect Bush doubles the whole bucket. Evie eats a player’s highest-value berry. Bucket Spill divides a bucket by two. Rain ends the hand.</p>',[{label:'Got It',action:closeModal}]);resetHand();
